---
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './packages/client/tsconfig.json'
    - './packages/coc-swagger/tsconfig.json'

extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - prettier/@typescript-eslint
  - react-app

root: true

env:
  node: true
  jest: true

globals:
  __DEV__: true

rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/camelcase': 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - { argsIgnorePattern: '^_' }
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false

  react-hooks/rules-of-hooks: error

#   quotes: ["error", "single"]
#   strict: ["error", "never"]
#   no-console: "warn"
